version: 1.0.{build}
skip_branch_with_pr: true
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- cmd: >-
    nuget restore

    cd LibPostalNet\x86

    curl -sSL -o "libpostal.zip" "https://ci.appveyor.com/api/buildjobs/y31gc0mddv3cbcy9/artifacts/libpostal.zip"

    7z.exe e libpostal.zip *.dll

    cd ..\x64

    curl -sSL -o "libpostal.zip" "https://ci.appveyor.com/api/buildjobs/9tw6iwxxmts1qaxv/artifacts/libpostal.zip"

    7z.exe e libpostal.zip *.dll

    cd ..\..\
build:
  project: LibPostalNet.sln
after_build:
- ps: |
   7z a libpostalnet.zip $Env:APPVEYOR_BUILD_FOLDER\*
artifacts:
- path: libpostalnet.zip
  name: libpostalnet
